name: test pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
      - name: Install dependencies
        run: dotnet restore
        working-directory: solution
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: solution
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: solution
