name: test pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
      - name: Install dependencies
        run: dotnet restore
        working-directory: solution
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: solution
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: solution
      - name: publish
        run: dotnet publish --no-restore
        working-directory: solution

  merge_job_pre_prod:
    needs: [build]
    # if: (github.ref == 'refs/heads/main') && needs.build.result == 'success'
    runs-on: ubuntu-latest
    environment: pre-prod
    steps:
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run Azure CLI commands"
        run: |
          az account show
          az group list
          pwd

      - name: Run Bicep deploy
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: resource-group-nonprod
          template: ./solution/infrastructure/infrastructure.bicep

  merge_job_prod:
    # this job will only run if the PR has been merged
    needs: [merge_job_pre_prod]
    if: needs.merge_job_pre_prod.result == 'success'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged
