name: test pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2

      - name: Install dependencies
        run: dotnet restore
        working-directory: solution/Challenge_One_Sol

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: solution/Challenge_One_Sol

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: solution/Challenge_One_Sol

      - name: Publish
        run: dotnet publish -c Release -o website
        working-directory: solution/Challenge_One_Sol

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: website
          path: solution/Challenge_One_Sol/website/**
          if-no-files-found: error

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: iac
          path: solution/Challenge_One_Sol/infrastructure/infrastructure.bicep
          if-no-files-found: error

  merge_job_pre_prod:
    needs: [build]
    if: (github.ref == 'refs/heads/main') && needs.build.result == 'success'
    runs-on: ubuntu-latest
    environment: pre-prod
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: website
          path: website

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: iac
          path: iac

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Bicep deploy
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: resource-group-nonprod
          template: iac/infrastructure.bicep
          parameters: env=nonprod

      - name: Deploy web app
        id: deploywebapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: appService-nonprod
          package: website

  merge_job_prod:
    needs: [merge_job_pre_prod]
    if: (github.ref == 'refs/heads/main') && needs.merge_job_pre_prod.result == 'success'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: website
          path: website

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: iac
          path: iac

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          parameters: env='prod'

      - name: Run Bicep deploy
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: resource-group-prod
          template: iac/infrastructure.bicep

      - name: Deploy web app
        id: deploywebapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: appService-prod
          package: website
